// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:chat_app/api_keys.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: webApiKey,
    appId: '1:139568961808:web:6b05587389a824a7dd2d95',
    messagingSenderId: '139568961808',
    projectId: 'chat-app-b75d0',
    authDomain: 'chat-app-b75d0.firebaseapp.com',
    storageBucket: 'chat-app-b75d0.appspot.com',
    measurementId: 'G-1T4EJRCL65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: '1:139568961808:android:bd5f7aea9c347025dd2d95',
    messagingSenderId: '139568961808',
    projectId: 'chat-app-b75d0',
    storageBucket: 'chat-app-b75d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: '1:139568961808:ios:a6c9c6a3d86d35e5dd2d95',
    messagingSenderId: '139568961808',
    projectId: 'chat-app-b75d0',
    storageBucket: 'chat-app-b75d0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: macosApiKey,
    appId: '1:139568961808:ios:a6c9c6a3d86d35e5dd2d95',
    messagingSenderId: '139568961808',
    projectId: 'chat-app-b75d0',
    storageBucket: 'chat-app-b75d0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: windowsApiKey,
    appId: '1:139568961808:web:c6b04b5451c74327dd2d95',
    messagingSenderId: '139568961808',
    projectId: 'chat-app-b75d0',
    authDomain: 'chat-app-b75d0.firebaseapp.com',
    storageBucket: 'chat-app-b75d0.appspot.com',
    measurementId: 'G-69JR1P4HHD',
  );
}
